"""Initial normalized storage and forecast audit ledger

Revision ID: 0001
Revises:
Created: 2026-09-30 01:56:03.347037
"""

import sqlalchemy as sa
from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "daily_reports",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("mode", sa.String(length=80), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("markdown", sa.String(), nullable=False),
        sa.Column("html", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "entities",
        sa.Column("id", sa.String(length=150), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("domain", sa.String(length=30), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("region", sa.String(length=30), nullable=False),
        sa.Column("keywords", sa.JSON(), nullable=False),
        sa.Column("primary_metric", sa.String(length=60), nullable=False),
        sa.Column("unit", sa.String(length=40), nullable=False),
        sa.Column("cadence", sa.String(length=30), nullable=False),
        sa.Column("synthetic", sa.Boolean(), nullable=False),
        sa.Column("analytics_allowed", sa.Boolean(), nullable=False),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_entities_domain"), "entities", ["domain"], unique=False)
    op.create_index(op.f("ix_entities_name"), "entities", ["name"], unique=False)
    op.create_table(
        "model_versions",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("card", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "providers",
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("capability", sa.String(length=30), nullable=False),
        sa.Column("message", sa.String(length=600), nullable=False),
        sa.Column("last_attempt", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expected_interval_hours", sa.Integer(), nullable=False),
        sa.Column("records", sa.Integer(), nullable=False),
        sa.Column("stats", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "events",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("entity_id", sa.String(length=150), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_events_entity_id"), "events", ["entity_id"], unique=False)
    op.create_table(
        "forecasts",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("entity_id", sa.String(length=150), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("horizon", sa.Integer(), nullable=False),
        sa.Column("horizon_unit", sa.String(length=30), nullable=False),
        sa.Column("target_metric", sa.String(length=60), nullable=False),
        sa.Column("target_provider", sa.String(length=80), nullable=False),
        sa.Column("model_version", sa.String(length=80), nullable=False),
        sa.Column("snapshot_hash", sa.String(length=64), nullable=False),
        sa.Column("features_hash", sa.String(length=64), nullable=False),
        sa.Column("reference_value", sa.Float(), nullable=False),
        sa.Column("threshold", sa.Float(), nullable=False),
        sa.Column("synthetic", sa.Boolean(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "entity_id", "snapshot_hash", "horizon", "model_version", name="uq_forecast_snapshot"
        ),
    )
    op.create_index(op.f("ix_forecasts_entity_id"), "forecasts", ["entity_id"], unique=False)
    op.create_index(op.f("ix_forecasts_issued_at"), "forecasts", ["issued_at"], unique=False)
    op.create_table(
        "model_metrics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("model_version", sa.String(length=80), nullable=False),
        sa.Column("measured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["model_version"],
            ["model_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "relationships",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.String(length=150), nullable=False),
        sa.Column("target_id", sa.String(length=150), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("measured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["entities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["entities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "trend_observations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entity_id", sa.String(length=150), nullable=False),
        sa.Column("provider", sa.String(length=80), nullable=False),
        sa.Column("metric", sa.String(length=60), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("source_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("unit", sa.String(length=40), nullable=False),
        sa.Column("source_url", sa.String(length=1000), nullable=True),
        sa.Column("synthetic", sa.Boolean(), nullable=False),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "entity_id", "provider", "metric", "source_timestamp", name="uq_observation"
        ),
    )
    op.create_index(
        op.f("ix_trend_observations_entity_id"), "trend_observations", ["entity_id"], unique=False
    )
    op.create_index(
        op.f("ix_trend_observations_provider"), "trend_observations", ["provider"], unique=False
    )
    op.create_index(
        op.f("ix_trend_observations_source_timestamp"),
        "trend_observations",
        ["source_timestamp"],
        unique=False,
    )
    op.create_table(
        "trend_scores",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entity_id", sa.String(length=150), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("calculated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("snapshot_hash", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("entity_id", "snapshot_hash", name="uq_score_snapshot"),
    )
    op.create_index(op.f("ix_trend_scores_as_of"), "trend_scores", ["as_of"], unique=False)
    op.create_index(op.f("ix_trend_scores_entity_id"), "trend_scores", ["entity_id"], unique=False)
    op.create_table(
        "watchlists",
        sa.Column("entity_id", sa.String(length=150), nullable=False),
        sa.Column("added_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entities.id"],
        ),
        sa.PrimaryKeyConstraint("entity_id"),
    )
    op.create_table(
        "forecast_outcomes",
        sa.Column("forecast_id", sa.String(length=40), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("evaluated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actual_value", sa.Float(), nullable=False),
        sa.Column("actual_return", sa.Float(), nullable=False),
        sa.Column("actual_class", sa.String(length=20), nullable=False),
        sa.Column("correct", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["forecast_id"],
            ["forecasts.id"],
        ),
        sa.PrimaryKeyConstraint("forecast_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("forecast_outcomes")
    op.drop_table("watchlists")
    op.drop_index(op.f("ix_trend_scores_entity_id"), table_name="trend_scores")
    op.drop_index(op.f("ix_trend_scores_as_of"), table_name="trend_scores")
    op.drop_table("trend_scores")
    op.drop_index(op.f("ix_trend_observations_source_timestamp"), table_name="trend_observations")
    op.drop_index(op.f("ix_trend_observations_provider"), table_name="trend_observations")
    op.drop_index(op.f("ix_trend_observations_entity_id"), table_name="trend_observations")
    op.drop_table("trend_observations")
    op.drop_table("relationships")
    op.drop_table("model_metrics")
    op.drop_index(op.f("ix_forecasts_issued_at"), table_name="forecasts")
    op.drop_index(op.f("ix_forecasts_entity_id"), table_name="forecasts")
    op.drop_table("forecasts")
    op.drop_index(op.f("ix_events_entity_id"), table_name="events")
    op.drop_table("events")
    op.drop_table("providers")
    op.drop_table("model_versions")
    op.drop_index(op.f("ix_entities_name"), table_name="entities")
    op.drop_index(op.f("ix_entities_domain"), table_name="entities")
    op.drop_table("entities")
    op.drop_table("daily_reports")
    # ### end Alembic commands ###
