import { useCallback, useEffect, useState } from 'react';
import type { FormEvent, ReactNode } from 'react';
import { Activity, ArrowDownRight, ArrowRight, ArrowUpRight, Bookmark, ChartNoAxesCombined, Check, ChevronLeft, ChevronRight, CircleHelp, Cpu, Database, Download, ExternalLink, FileText, FlaskConical, GitCompareArrows, Globe2, Layers3, LayoutDashboard, Menu, Radio, Radar as RadarIcon, RefreshCw, Search, Settings2, ShieldCheck, SlidersHorizontal, Sparkles, TrendingUp, X, Zap } from 'lucide-react';
import { api, download, setAccessToken } from './api';
import { LineChart, Radar } from './charts';
import type { Backtest, Event, Evidence, Forecast, History, Provider, Relationship, TrackRecord, Trend } from './types';

const domainNames: Record<string, string> = { stocks: 'Markets', technology: 'Technology', youtube: 'YouTube', fashion: 'Fashion', search: 'Search', entertainment: 'Entertainment', crypto: 'Crypto', news: 'News', general: 'General' };
const navigation = [
  ['overview', 'Overview', LayoutDashboard], ['discovery', 'Discover signals', Sparkles], ['radar', 'Trend radar', RadarIcon], ['compare', 'Compare', GitCompareArrows], ['watchlist', 'Watchlist', Bookmark], ['reports', 'Daily reports', FileText], ['research', 'Research lab', FlaskConical], ['providers', 'Data providers', Database],
] as const;
const fmt = (value: number | undefined, digits = 1) => value === undefined ? '—' : value.toLocaleString('en-US', { maximumFractionDigits: digits });
const pct = (value: number | undefined, digits = 1) => value === undefined ? '—' : `${value > 0 ? '+' : ''}${value.toFixed(digits)}%`;
const date = (value: string | null | undefined, full = false) => value ? new Date(value).toLocaleString('en-GB', { day: '2-digit', month: 'short', ...(full ? { year: 'numeric', hour: '2-digit', minute: '2-digit' } : {}), timeZone: 'UTC' }) : 'Not available';
const trendColor = (trend: Trend) => (trend.score.growth_7_periods ?? 0) < 0 ? 'var(--coral)' : 'var(--lime)';

function Badge({ children, tone = 'neutral' }: { children: ReactNode; tone?: string }) { return <span className={`badge ${tone}`}>{children}</span>; }
function Empty({ title, children }: { title: string; children?: ReactNode }) { return <div className="empty-state"><Radio size={32} /><h3>{title}</h3><p>{children}</p></div>; }
function PanelTitle({ eyebrow, title, action }: { eyebrow?: string; title: string; action?: ReactNode }) { return <div className="panel-title"><div>{eyebrow && <span className="micro">{eyebrow}</span>}<h2>{title}</h2></div>{action}</div>; }
function Probability({ forecast }: { forecast: Forecast }) {
  return <div className="probability"><div className="probability-bars" aria-label={`Up ${fmt(forecast.probabilities.up * 100)}%, sideways ${fmt(forecast.probabilities.sideways * 100)}%, down ${fmt(forecast.probabilities.down * 100)}%`}><i style={{ width: `${forecast.probabilities.up * 100}%` }} /><i style={{ width: `${forecast.probabilities.sideways * 100}%` }} /><i style={{ width: `${forecast.probabilities.down * 100}%` }} /></div><div className="probability-labels"><span><i className="dot lime" />Growth <b>{fmt(forecast.probabilities.up * 100)}%</b></span><span><i className="dot amber" />Sideways <b>{fmt(forecast.probabilities.sideways * 100)}%</b></span><span><i className="dot coral" />Decline <b>{fmt(forecast.probabilities.down * 100)}%</b></span></div></div>;
}

export default function App() {
  const [page, setPage] = useState(location.hash.slice(1) || 'overview');
  const [trends, setTrends] = useState<Trend[]>([]);
  const [providers, setProviders] = useState<Provider[]>([]);
  const [events, setEvents] = useState<Event[]>([]);
  const [record, setRecord] = useState<TrackRecord | null>(null);
  const [mode, setMode] = useState('CONNECTING');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState('');
  const [domain, setDomain] = useState('');
  const [region, setRegion] = useState('');
  const [sort, setSort] = useState('score');
  const [menu, setMenu] = useState(false);
  const [settings, setSettings] = useState(false);
  const [token, setToken] = useState('');
  const [notice, setNotice] = useState('');

  const load = useCallback(async () => {
    setLoading(true); setError('');
    try {
      const [items, sources, alerts, track, health] = await Promise.all([
        api<{ items: Trend[] }>('/api/trends'), api<{ items: Provider[] }>('/api/providers/status'), api<{ items: Event[] }>('/api/events'), api<TrackRecord>('/api/models/track-record'), api<{ mode: string }>('/api/system/health'),
      ]);
      setTrends(items.items); setProviders(sources.items); setEvents(alerts.items); setRecord(track); setMode(health.mode);
    } catch (e) { setError((e as Error).message); } finally { setLoading(false); }
  }, []);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { const onHash = () => { setPage(location.hash.slice(1) || 'overview'); setMenu(false); window.scrollTo(0, 0); }; window.addEventListener('hashchange', onHash); return () => window.removeEventListener('hashchange', onHash); }, []);
  useEffect(() => { if (!notice) return; const timeout = window.setTimeout(() => setNotice(''), 5000); return () => clearTimeout(timeout); }, [notice]);
  const navigate = (next: string) => { location.hash = next; setMenu(false); };
  const openTrend = (id: string) => navigate(`trend/${encodeURIComponent(id)}`);
  const toggleWatch = async (trend: Trend) => {
    try {
      if (trend.watchlisted) await api(`/api/watchlist/${encodeURIComponent(trend.id)}`, { method: 'DELETE' });
      else await api('/api/watchlist', { method: 'POST', body: JSON.stringify({ entity_id: trend.id }) });
      setTrends(items => items.map(t => t.id === trend.id ? { ...t, watchlisted: !t.watchlisted } : t));
      setNotice(trend.watchlisted ? 'Removed from your watchlist' : 'Added to your watchlist');
    } catch (e) { setNotice((e as Error).message); }
  };
  const filtered = trends.filter(t => (!domain || t.domain === domain) && (!region || t.region === region) && (!search || `${t.name} ${t.id} ${t.category}`.toLowerCase().includes(search.toLowerCase()))).sort((a, b) => {
    const key = sort === 'acceleration' ? 'relative_acceleration' : sort === 'emerging' ? 'early_signal_score' : sort === 'cooling' ? 'growth_7_periods' : 'current_score';
    return ((b.score[key] ?? 0) - (a.score[key] ?? 0)) * (sort === 'cooling' ? -1 : 1);
  });
  const demo = mode === 'MOCK/DEMO';
  const latest = trends.map(t => t.last_updated).filter(Boolean).sort().at(-1);
  const watchCount = trends.filter(t => t.watchlisted).length;

  return <div className="app-shell">
    <a href="#main-content" className="skip-link" onClick={e => { e.preventDefault(); document.getElementById('main-content')?.focus(); }}>Skip to content</a>
    {menu && <button className="sidebar-scrim" aria-label="Close navigation" onClick={() => setMenu(false)} />}
    <aside className={`sidebar ${menu ? 'open' : ''}`}>
      <a className="brand" href="#overview"><img src="/icon.svg" alt="" /><span>TrendForge<small>INTELLIGENCE ENGINE</small></span><b>AI</b></a>
      <div className="workspace"><span className="workspace-avatar">TF</span><div>Research workspace<small>{demo ? 'Synthetic sandbox' : 'Local workspace'}</small></div><ChevronRight size={14} /></div>
      <span className="nav-label">WORKSPACE</span>
      <nav aria-label="Main navigation">{navigation.map(([id, label, Icon]) => <a href={`#${id}`} key={id} className={page === id ? 'active' : ''} onClick={() => setMenu(false)}><Icon size={18} /><span>{label}</span>{id === 'watchlist' && watchCount > 0 && <b>{watchCount}</b>}{id === 'research' && <span className="tiny-pill">LAB</span>}</a>)}</nav>
      <span className="nav-label">EXPLORE DOMAINS</span>
      <nav aria-label="Domain filters" className="domain-nav">{Object.entries(domainNames).filter(([id]) => trends.some(t => t.domain === id)).map(([id, name]) => <button key={id} className={domain === id ? 'selected' : ''} onClick={() => { setDomain(id); navigate('discovery'); }}><i className={`domain-dot ${id}`} /><span>{name}</span><small>{trends.filter(t => t.domain === id).length}</small></button>)}</nav>
      <div className="sidebar-bottom"><ShieldCheck size={20} /><strong>Evidence over noise.</strong><p>Every signal has a source.<br />Every forecast has a history.</p><a href="/docs" target="_blank" rel="noreferrer">Explore the API <ExternalLink size={13} /></a><span className="version">v0.1.0 · OPEN SOURCE</span></div>
    </aside>
    <div className="main-shell">
      <header className="topbar"><button className="icon-button mobile-menu" onClick={() => setMenu(!menu)} aria-label="Open navigation"><Menu size={21} /></button><div className="breadcrumbs">Workspace <ChevronRight size={13} /><span>{page.startsWith('trend/') ? 'Trend intelligence' : navigation.find(n => n[0] === page)?.[1] || 'Overview'}</span></div><div className="topbar-actions"><span className="connection"><i className={`dot ${error ? 'coral' : 'lime'}`} />{error ? 'Disconnected' : loading ? 'Connecting' : 'API connected'}</span><button className="icon-button" title="Reload stored data" onClick={() => void load()} aria-label="Reload stored data" disabled={loading}><RefreshCw size={16} className={loading ? 'spin' : ''} /></button><button className="icon-button" aria-label="Connection settings" onClick={() => setSettings(true)}><Settings2 size={17} /></button><span className="avatar">TF</span></div></header>
      <main id="main-content" tabIndex={-1}>
        <div className={`mode-banner ${demo ? '' : 'live-banner'}`}><span><Radio size={14} />{demo ? 'DEMO WORKSPACE' : mode}</span><p>{demo ? 'All trend values and forecasts below use synthetic data. No current market or platform claims.' : 'Provider timestamps and capability limits are shown with each signal.'}</p><button onClick={() => navigate('providers')}>Data sources <ArrowRight size={14} /></button></div>
        {error ? <div className="error-panel" role="alert"><h2>Let’s reconnect the data.</h2><p>{error}</p><p>Start the backend with <code>trendforge serve</code>. In live mode, enter your workspace API access token in connection settings.</p><button className="button primary" onClick={() => void load()}>Try again</button><button className="button" onClick={() => setSettings(true)}>Connection settings</button></div> : loading && !trends.length ? <div className="loading-panel"><Activity className="spin" /><h2>Reading the signals…</h2></div> : <>
          {page.startsWith('trend/') ? <Detail key={page} id={decodeURIComponent(page.slice(6))} trend={trends.find(t => t.id === decodeURIComponent(page.slice(6)))} onWatch={toggleWatch} onBack={() => navigate('overview')} onError={setNotice} /> : <>
            <div className="page-heading"><div><span className="micro accent">TRENDFORGE / {page === 'overview' ? 'SIGNAL INTELLIGENCE' : page.toUpperCase()}</span><h1>{({ overview: 'The signal before the noise.', discovery: 'Find your next signal.', radar: 'A different view of momentum.', compare: 'Put the signals side by side.', watchlist: 'Keep the right signals close.', reports: 'Your daily intelligence brief.', research: 'Question the model.', providers: 'Know where the data comes from.' } as Record<string, string>)[page] || 'Explore the signals.'}</h1><p>{page === 'overview' ? 'Observe what’s changing. Understand the evidence. Explore what could come next.' : page === 'providers' ? 'Configured capabilities, last successful retrievals, and honest limitations.' : 'Transparent observations. Measured analysis. Probabilistic forecasts.'}</p></div>{page === 'overview' && <div className="as-of"><i className="dot cyan" /><span>OBSERVATIONS THROUGH<strong>{date(latest)} · UTC</strong></span></div>}</div>
            {['overview', 'discovery', 'watchlist', 'radar'].includes(page) && <div className="filter-bar"><label className="search-field"><Search size={18} /><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search topics, stocks, technologies…" aria-label="Search trends" />{search && <button aria-label="Clear search" onClick={() => setSearch('')}><X size={14} /></button>}</label><label className="select-field"><Globe2 size={16} /><select value={region} onChange={e => setRegion(e.target.value)} aria-label="Filter by region"><option value="">All regions</option>{[...new Set(trends.map(t => t.region))].map(r => <option key={r}>{r}</option>)}</select></label><label className="select-field"><SlidersHorizontal size={16} /><select value={sort} onChange={e => setSort(e.target.value)} aria-label="Sort trends"><option value="score">Trend strength</option><option value="acceleration">Acceleration</option><option value="emerging">Early signals</option><option value="cooling">Cooling fastest</option></select></label></div>}
            {['overview', 'discovery', 'radar'].includes(page) && <div className="domain-tabs" role="group" aria-label="Domains"><button className={!domain ? 'active' : ''} onClick={() => setDomain('')}>All signals <span>{trends.length}</span></button>{Object.entries(domainNames).filter(([id]) => trends.some(t => t.domain === id)).map(([id, name]) => <button key={id} className={domain === id ? 'active' : ''} onClick={() => setDomain(id)}>{name}</button>)}</div>}
            {page === 'overview' && <Overview trends={filtered} allTrends={trends} providers={providers} events={events} record={record} onOpen={openTrend} onWatch={toggleWatch} navigate={navigate} />}
            {page === 'discovery' && <div className="panel"><PanelTitle title="Signal discovery" eyebrow={`${filtered.length} MATCHING ENTITIES`} action={<Badge tone="cyan">Ranked by evidence</Badge>} /><TrendTable trends={filtered} onOpen={openTrend} onWatch={toggleWatch} /></div>}
            {page === 'watchlist' && <div className="panel"><PanelTitle title="Saved signals" eyebrow="PERSISTED TO YOUR LOCAL WORKSPACE" /><TrendTable trends={filtered.filter(t => t.watchlisted)} onOpen={openTrend} onWatch={toggleWatch} empty="Your watchlist is ready." emptyText="Save a trend using the bookmark button to keep its evidence, forecast and freshness in view." /></div>}
            {page === 'radar' && <div className="grid-two"><section className="panel"><PanelTitle title="Trend radar" eyebrow="MOMENTUM × MATURITY" /><Radar trends={filtered} onOpen={openTrend} /><p className="panel-note">Lifecycle positions are heuristic. Dot size represents acceleration. All current baseline forecasts have LOW or VERY LOW confidence.</p></section><section className="panel"><PanelTitle title="Domain heatmap" eyebrow="TREND STRENGTH / 0–100" /><div className="heatmap">{filtered.map(t => <button key={t.id} onClick={() => openTrend(t.id)} style={{ background: `rgba(196,246,107,${.025 + (t.score.current_score ?? 0) / 700})` }}><small>{domainNames[t.domain]}</small><strong>{fmt(t.score.current_score, 0)}</strong><span>{t.name}</span><small>{t.score.lifecycle_stage || 'No score'}</small></button>)}</div></section></div>}
            {page === 'compare' && <Compare trends={trends} onOpen={openTrend} onError={setNotice} />}
            {page === 'providers' && <Providers providers={providers} />}
            {page === 'reports' && <Reports onError={setNotice} />}
            {page === 'research' && <Research trends={trends} record={record} onError={setNotice} />}
          </>}
        </>}
        <footer><span><ChartNoAxesCombined size={16} /> TRENDFORGE AI <small>Detect · Understand · Compare · Forecast</small></span><p>Research and educational analytics only. Forecasts are probabilistic and may be wrong.</p><div><a href="https://www.youtube.com/t/terms" target="_blank" rel="noreferrer">YouTube terms</a><a href="https://policies.google.com/privacy" target="_blank" rel="noreferrer">Google privacy</a></div></footer>
      </main>
    </div>
    {notice && <div className="toast" role="status"><Check size={17} />{notice}<button aria-label="Dismiss notification" onClick={() => setNotice('')}><X size={15} /></button></div>}
    {settings && <div className="modal-backdrop" onClick={() => setSettings(false)}><section role="dialog" aria-modal="true" aria-labelledby="settings-title" className="settings-modal" onClick={e => e.stopPropagation()}><button className="icon-button close-modal" onClick={() => setSettings(false)} aria-label="Close settings"><X /></button><span className="micro accent">WORKSPACE CONNECTION</span><h2 id="settings-title">Connection settings</h2><p>The workspace API token grants access to your backend. Provider API keys belong only in the server’s environment.</p><form onSubmit={e => { e.preventDefault(); setAccessToken(token); setSettings(false); void load(); }}><label>Workspace API access token<input type="password" value={token} onChange={e => setToken(e.target.value)} autoComplete="off" autoFocus placeholder="Leave empty for local demo mode" /></label><p className="muted small">Kept in memory for this browser session. Your watchlist is saved in the backend database.</p><button className="button primary" type="submit">Connect workspace <ArrowRight size={16} /></button></form><hr /><h3>Refresh behavior</h3><p className="small">The refresh button reloads stored results. Data collection runs through <code>trendforge update</code> or the included daily workflow.</p></section></div>}
  </div>;
}

function TrendTable({ trends, onOpen, onWatch, empty = 'No signals match these filters.', emptyText = 'Try another search or enable a data provider.' }: { trends: Trend[]; onOpen: (id: string) => void; onWatch: (t: Trend) => void; empty?: string; emptyText?: string }) {
  if (!trends.length) return <Empty title={empty}>{emptyText}</Empty>;
  return <div className="table-scroll"><table className="trend-table"><thead><tr><th>Signal / domain</th><th>Trend score</th><th>Observed activity</th><th>7 periods</th><th>Lifecycle</th><th>Forecast / growth</th><th><span className="sr-only">Watchlist</span></th></tr></thead><tbody>{trends.map((t, i) => <tr key={t.id}><td><button className="entity-link" onClick={() => onOpen(t.id)}><span className={`entity-icon domain-${t.domain}`}>{t.domain === 'stocks' ? <TrendingUp size={19} /> : t.domain === 'technology' ? <Cpu size={19} /> : t.domain === 'youtube' ? <Radio size={19} /> : <Layers3 size={19} />}</span><span><strong>{t.name}</strong><small>{domainNames[t.domain]} <i>·</i> {t.region}</small></span></button></td><td><div className="score-cell"><strong>{fmt(t.score.current_score, 0)}</strong><span>/100</span></div><div className="mini-meter"><i style={{ width: `${t.score.current_score ?? 0}%`, background: trendColor(t) }} /></div></td><td><LineChart points={t.sparkline} compact color={trendColor(t)} label={t.name} /></td><td className={(t.score.growth_7_periods ?? 0) < 0 ? 'negative' : 'positive'}><span className="change">{(t.score.growth_7_periods ?? 0) < 0 ? <ArrowDownRight size={14} /> : <ArrowUpRight size={14} />}{pct(t.score.growth_7_periods)}</span><small className="muted">{t.freshness.status}</small></td><td><Badge tone={['Declining', 'Cooling'].includes(t.score.lifecycle_stage || '') ? 'coral' : i % 2 ? 'cyan' : 'lime'}>{t.score.lifecycle_stage || 'Raw statistics'}</Badge></td><td>{t.forecast ? <><strong className="forecast-number">{fmt(t.forecast.probabilities.up * 100, 0)}% <ArrowUpRight size={13} /></strong><small className="muted">{t.forecast.horizon}{t.cadence === 'trading_session' ? ' sessions' : ' days'} · {t.forecast.confidence}</small></> : <small className="muted">{t.forecast_status}</small>}</td><td><button className={`icon-button bookmark ${t.watchlisted ? 'saved' : ''}`} onClick={() => onWatch(t)} aria-label={`${t.watchlisted ? 'Remove' : 'Save'} ${t.name}`}><Bookmark size={17} fill={t.watchlisted ? 'currentColor' : 'none'} /></button></td></tr>)}</tbody></table></div>;
}

function Overview({ trends, allTrends, providers, events, record, onOpen, onWatch, navigate }: { trends: Trend[]; allTrends: Trend[]; providers: Provider[]; events: Event[]; record: TrackRecord | null; onOpen: (id: string) => void; onWatch: (t: Trend) => void; navigate: (p: string) => void }) {
  const stats = [
    { name: 'Signals tracked', value: trends.length, subtitle: `${new Set(trends.map(t => t.domain)).size} active domains`, icon: Activity, tone: 'cyan' },
    { name: 'Accelerating', value: trends.filter(t => (t.score.relative_acceleration ?? 0) > 0).length, subtitle: 'Growth gaining pace', icon: Zap, tone: 'lime' },
    { name: 'Breakout watch', value: trends.filter(t => (t.score.early_signal_score ?? 0) >= 65).length, subtitle: 'Early signal score ≥ 65', icon: RadarIcon, tone: 'violet' },
    { name: 'Cooling signals', value: trends.filter(t => (t.score.growth_7_periods ?? 0) < 0).length, subtitle: 'Negative 7-period change', icon: ArrowDownRight, tone: 'coral' },
  ];
  const spotlight = trends[0];
  const watch = [...trends].sort((a, b) => (b.score.early_signal_score ?? 0) - (a.score.early_signal_score ?? 0)).slice(0, 3);
  return <><div className="stats-grid">{stats.map(s => <div className={`stat-card ${s.tone}`} key={s.name}><div><span>{s.name}</span><s.icon size={18} /></div><strong>{s.value.toString().padStart(2, '0')}</strong><small><span className={`dot ${s.tone}`} />{s.subtitle}</small></div>)}</div>
    <div className="overview-top"><section className="panel spotlight"><PanelTitle title="Signal spotlight" eyebrow="HIGHEST RANKED IN THIS VIEW" action={<Badge tone="lime"><i className="dot lime" />Observed activity</Badge>} />{spotlight ? <><div className="spotlight-heading"><button onClick={() => onOpen(spotlight.id)}>{spotlight.name}<ArrowUpRight size={21} /></button><div><strong>{fmt(spotlight.score.current_score, 0)}<small>/100</small></strong><Badge tone="cyan">{spotlight.score.lifecycle_stage || 'Raw data'}</Badge></div></div><LineChart points={spotlight.sparkline} label={spotlight.name} unit={spotlight.unit} /><div className="spotlight-bottom"><span>7-PERIOD CHANGE<strong className={(spotlight.score.growth_7_periods ?? 0) < 0 ? 'negative' : 'positive'}>{pct(spotlight.score.growth_7_periods)}</strong></span><span>DATA QUALITY<strong>{fmt(spotlight.score.quality?.score, 0)}<small>/100</small></strong></span><span>FORECAST CONFIDENCE<strong className="amber-text">{spotlight.forecast?.confidence || 'Unavailable'}</strong></span></div></> : <Empty title="No matching history">Adjust your filters to explore a signal.</Empty>}</section>
    <section className="panel radar-panel"><PanelTitle title="The trend landscape" eyebrow="DISCOVER / EXPLORE" action={<button className="icon-button" onClick={() => navigate('radar')} aria-label="Open full trend radar"><ArrowUpRight size={19} /></button>} /><Radar trends={trends} onOpen={onOpen} /></section></div>
    <section className="panel signal-panel"><PanelTitle title="Signals worth watching" eyebrow="THE OBSERVATION DESK" action={<button className="text-button" onClick={() => navigate('discovery')}>Explore all signals <ArrowRight size={15} /></button>} /><TrendTable trends={trends.slice(0, 7)} onOpen={onOpen} onWatch={onWatch} /></section>
    <div className="section-heading"><div><span className="micro">SMALL SIGNALS. POSSIBLE SHIFTS.</span><h2>Early signal watch</h2></div><span className="muted small">Heuristic scores · not probabilities</span></div><div className="watch-grid">{watch.map((t, i) => <button className="watch-card" key={t.id} onClick={() => onOpen(t.id)}><div><span className="micro">0{i + 1} / {domainNames[t.domain]?.toUpperCase()}</span><ArrowUpRight size={19} /></div><h3>{t.name}</h3><div className="watch-data"><span><strong>{fmt(t.score.early_signal_score, 0)}</strong><small>EARLY SIGNAL SCORE</small></span><LineChart points={t.sparkline} compact color={['var(--lime)', 'var(--cyan)', 'var(--violet)'][i]} /></div><span className="watch-foot">{t.score.lifecycle_stage} <span>Explore evidence <ChevronRight size={14} /></span></span></button>)}</div>
    <div className="overview-bottom"><section className="panel"><PanelTitle title="Recent signal events" eyebrow="INTERNAL ALERTS" /><div className="event-list">{events.slice(0, 4).map(e => <button key={e.id} onClick={() => onOpen(e.entity_id)}><span className="event-icon"><Activity size={16} /></span><span><strong>{e.name}</strong><small>{e.message}</small></span><time>{date(e.occurred_at)}</time></button>)}{!events.length && <p className="muted">No alert thresholds have been reached.</p>}</div></section><section className="panel trust-panel"><PanelTitle title="Trust is a track record." eyebrow="BUILT FOR ACCOUNTABILITY" /><p>Predictions are stored before outcomes are known. The misses stay in the record.</p><div className="trust-stats"><span><strong>{record?.issued ?? 0}</strong>Forecasts stored</span><span><strong>{record?.resolved ?? 0}</strong>Outcomes resolved</span><span><strong>{providers.filter(p => p.status === 'ONLINE').length}</strong>Available sources</span></div><div className="subtle-notice"><ShieldCheck size={16} />{allTrends.every(t => t.synthetic) ? 'Demo probabilities show the method, not real-world performance.' : 'Live calibration starts with prospective observations.'}</div><button className="text-button" onClick={() => navigate('research')}>Inspect the methodology <ArrowRight size={15} /></button></section></div>
  </>;
}

function Detail({ id, trend, onWatch, onBack, onError }: { id: string; trend?: Trend; onWatch: (t: Trend) => void; onBack: () => void; onError: (message: string) => void }) {
  const [detail, setDetail] = useState<Trend | null>(null);
  const [history, setHistory] = useState<History | null>(null);
  const [forecasts, setForecasts] = useState<Forecast[]>([]);
  const [evidence, setEvidence] = useState<Evidence[]>([]);
  const [tab, setTab] = useState('overview');
  const [chart, setChart] = useState('observed');
  const [range, setRange] = useState(90);
  const [failed, setFailed] = useState('');
  useEffect(() => { let alive = true; Promise.all([api<Trend>(`/api/trends/${encodeURIComponent(id)}`), api<History>(`/api/trends/${encodeURIComponent(id)}/history`), api<{ items: Forecast[] }>(`/api/trends/${encodeURIComponent(id)}/forecast`), api<{ items: Evidence[] }>(`/api/trends/${encodeURIComponent(id)}/evidence`)]).then(([d, h, f, e]) => { if (alive) { setDetail(d); setHistory(h); setForecasts(f.items); setEvidence(e.items); } }).catch(e => { if (alive) setFailed(e.message); }); return () => { alive = false; }; }, [id]);
  const item = detail ? { ...detail, watchlisted: trend?.watchlisted ?? detail.watchlisted } : trend;
  if (failed) return <Empty title="This trend could not be loaded.">{failed}</Empty>;
  if (!item) return <Empty title="Loading the evidence…" />;
  const score = item.score;
  const latestForecasts = [...new Map([...forecasts].reverse().map(f => [f.horizon, f])).values()].sort((a, b) => a.horizon - b.horizon);
  const primaryForecast = item.forecast;
  return <><button className="text-button back-button" onClick={onBack}><ChevronLeft size={16} />All signals</button><div className="detail-heading"><div><span className="micro accent">{domainNames[item.domain]?.toUpperCase()} / {item.region} / {item.synthetic ? 'SYNTHETIC' : 'PROVIDER DATA'}</span><h1>{item.name}</h1><div className="detail-badges"><Badge tone="cyan">{score.lifecycle_stage || 'Raw statistics only'}</Badge><Badge tone={item.freshness.status === 'STALE' ? 'coral' : 'neutral'}>{item.freshness.status}</Badge><span className="muted small">Observed {date(item.last_updated, true)} UTC</span></div></div><div className="detail-score"><strong>{fmt(score.current_score, 0)}</strong><span>TREND SCORE / 100</span><button className={`button ${item.watchlisted ? 'saved' : ''}`} onClick={() => onWatch(item)}><Bookmark size={16} fill={item.watchlisted ? 'currentColor' : 'none'} />{item.watchlisted ? 'Saved' : 'Add to watchlist'}</button></div></div>
    {item.domain === 'stocks' && <div className="financial-notice"><ShieldCheck size={18} /><p>Research and educational analytics only. Forecasts are probabilistic and may be wrong.</p></div>}
    {!item.analytics_allowed && <div className="financial-notice"><CircleHelp size={18} /><p>This source supports raw statistics only. Custom trend scores and forecasts are disabled under the provider’s default policies.</p></div>}
    <div className="domain-tabs detail-tabs">{['overview', 'forecasts', 'analogues', 'evidence', 'timeline'].map(t => <button key={t} className={tab === t ? 'active' : ''} onClick={() => setTab(t)}>{t === 'evidence' ? 'Sources & evidence' : t[0].toUpperCase() + t.slice(1)}</button>)}</div>
    {tab === 'overview' && <><div className="detail-grid"><section className="panel"><PanelTitle title={chart === 'observed' ? 'Observed activity' : 'Recorded score history'} eyebrow={`${item.primary_metric.toUpperCase()} / UTC`} action={<div className="segmented">{[30, 90, 600].map(n => <button key={n} className={range === n ? 'active' : ''} onClick={() => setRange(n)}>{n === 600 ? 'All' : `${n} obs`}</button>)}</div>} /><div className="chart-tabs"><button className={chart === 'observed' ? 'active' : ''} onClick={() => setChart('observed')}>Primary metric</button><button className={chart === 'score' ? 'active' : ''} onClick={() => setChart('score')}>Trend score</button></div><LineChart points={chart === 'observed' ? history?.observations.slice(-range) || [] : history?.scores.slice(-range).map(s => ({ date: s.date, value: s.score })) || []} unit={chart === 'observed' ? item.unit : 'score / 100'} label={`${item.name} ${chart}`} /><p className="panel-note">Source: {score.primary_provider || evidence[0]?.provider || 'unavailable'} · Retrieved {date(item.freshness.retrieved_at, true)} UTC. Score history contains actual recorded runs, without fabricated backfills.</p></section><section className="panel"><PanelTitle title="What the evidence says" eyebrow="OBSERVATION → INFERENCE" /><div className="evidence-chain">{[['01', 'Observation', score.observation], ['02', 'Analysis', score.analysis], ['03', 'Inference', score.inference]].map(([n, label, text]) => <div key={n}><b>{n}</b><span><small>{label}</small><p>{text || 'Not available for this source.'}</p></span></div>)}</div><div className="subtle-notice"><CircleHelp size={16} />Lifecycle is a heuristic classification, not an established fact.</div></section></div>
      <div className="grid-two"><section className="panel"><PanelTitle title="Signal anatomy" eyebrow="AVAILABLE SCORE COMPONENTS" /><div className="component-list">{Object.entries(score.components || {}).map(([name, value]) => <div key={name}><span>{name.replaceAll('_', ' ')}</span><div className="component-track"><i style={{ width: `${value || 0}%` }} /></div><strong>{value === null ? 'N/A' : fmt(value, 0)}</strong></div>)}</div><p className="panel-note">Missing metrics are excluded and weights renormalized. Weight coverage: {fmt((score.weight_coverage || 0) * 100, 0)}%. A single source cannot confirm cross-platform breadth.</p></section><section className="panel"><PanelTitle title="A balanced reading" eyebrow="SUPPORTING & CONTRADICTING SIGNALS" /><h3 className="signal-subtitle positive">Supporting observations</h3><ul className="signal-list">{score.supporting_signals?.map(s => <li key={s}><span className="dot lime" />{s}</li>)}</ul><h3 className="signal-subtitle amber-text">Limitations & counter-signals</h3><ul className="signal-list">{score.contradicting_signals?.map(s => <li key={s}><span className="dot amber" />{s}</li>)}</ul></section></div>
      {score.technicals && <section className="panel technical-panel"><PanelTitle title="Financial technical overview" eyebrow="CAUSAL INDICATORS / ASSET-LEVEL REGIME" /><div className="technical-grid">{Object.entries(score.technicals).filter(([k]) => !['status', 'regime_scope'].includes(k)).map(([k, v]) => <div key={k}><small>{k.replaceAll('_', ' ')}</small><strong>{typeof v === 'number' ? fmt(v, 3) : v || 'Unavailable'}</strong></div>)}</div><p className="panel-note">{score.technicals.regime_scope}</p></section>}
    </>}
    {tab === 'forecasts' && <><div className="forecast-grid">{latestForecasts.map(f => <section className="panel forecast-card" key={f.id}><div className="forecast-card-heading"><h2>{f.horizon} {f.horizon_unit}</h2><Badge tone="amber">{f.confidence}</Badge></div><Probability forecast={f} /><p className="small muted">{f.class_definition}</p><div className="forecast-facts"><span>Analogues<strong>{f.analogue_count}</strong></span><span>Similarity<strong>{fmt(f.analogue_similarity * 100, 0)}%</strong></span><span>Calibration<strong>{f.calibration}</strong></span></div>{f.out_of_distribution && <p className="negative">Out-of-distribution conditions detected.</p>}<ul className="reason-list">{f.confidence_reasons.map(r => <li key={r}>{r}</li>)}</ul><span className="micro">ISSUED {date(f.issued_at, true)} UTC</span><button className="text-button" onClick={() => download(`/api/forecasts/${f.id}/audit`, `trendforge-audit-${f.id}.json`).catch(e => onError(e.message))}><Download size={15} />Export full audit snapshot</button></section>)}</div>{!forecasts.length ? <Empty title="No eligible forecast yet.">{item.forecast_status}. Forecasts require sufficient history and fresh data.</Empty> : <section className="panel"><PanelTitle title="Forecast history" eyebrow="MISSES AND HITS REMAIN IN THE RECORD" /><div className="table-scroll"><table><thead><tr><th>Issued (UTC)</th><th>Horizon</th><th>Growth estimate</th><th>Confidence</th><th>Actual result</th></tr></thead><tbody>{forecasts.map(f => <tr key={f.id}><td>{date(f.issued_at, true)}</td><td>{f.horizon} {f.horizon_unit}</td><td>{fmt(f.probabilities.up * 100)}%</td><td>{f.confidence}</td><td>{f.outcome ? `${f.outcome.actual_class.toUpperCase()} ${pct(f.outcome.actual_return * 100)}` : <Badge>Pending outcome</Badge>}</td></tr>)}</tbody></table></div></section>}</>}
    {tab === 'analogues' && <section className="panel"><PanelTitle title="Historical analogue search" eyebrow="NON-OVERLAPPING WINDOWS / KNOWN OUTCOMES ONLY" /><p className="panel-note">These historical windows and their outcomes end before the current query window begins. Similarity does not guarantee the future.</p>{primaryForecast ? <div className="table-scroll"><table><thead><tr><th>Pattern start (UTC)</th><th>Pattern end (UTC)</th><th>Similarity</th><th>Outcome date (UTC)</th><th>Subsequent change</th><th>Class</th></tr></thead><tbody>{primaryForecast.analogues.map(a => <tr key={a.start_date}><td>{date(a.start_date, true)}</td><td>{date(a.end_date, true)}</td><td>{fmt(a.similarity * 100)}%</td><td>{date(a.outcome_date, true)}</td><td className={a.future_return >= 0 ? 'positive' : 'negative'}>{pct(a.future_return * 100)}</td><td>{a.outcome}</td></tr>)}</tbody></table></div> : <Empty title="Not enough eligible analogues." />}</section>}
    {tab === 'evidence' && <section className="panel"><PanelTitle title="Raw evidence desk" eyebrow={`${evidence.length} RECENT OBSERVATIONS / UTC`} action={<button className="button" onClick={() => download(`/api/trends/${encodeURIComponent(id)}/evidence?limit=2000`, 'trendforge-evidence.json').catch(e => onError(e.message))}><Download size={15} />Export JSON</button>} /><div className="quality-banner"><span>Data quality <strong>{fmt(score.quality?.score, 0)}/100</strong></span><span>Historical samples <strong>{score.sample_size ?? 'N/A'}</strong></span><span>Independent sources <strong>{score.source_count ?? 'N/A'}</strong></span></div>{score.quality?.flags.map(f => <p key={f} className="panel-note amber-text">{f}</p>)}<div className="table-scroll evidence-table"><table><thead><tr><th>Metric</th><th>Value / unit</th><th>Source</th><th>Observed (UTC)</th><th>Retrieved (UTC)</th><th>Data type</th></tr></thead><tbody>{evidence.slice(0, 100).map(e => <tr key={e.id}><td>{e.metric}</td><td>{fmt(e.value, 3)} <small className="muted">{e.unit}</small></td><td>{e.source_url ? <a href={e.source_url} target="_blank" rel="noreferrer">{e.provider}<ExternalLink size={12} /></a> : e.provider}</td><td>{date(e.source_timestamp, true)}</td><td>{date(e.retrieved_at, true)}</td><td><Badge tone={e.synthetic ? 'amber' : 'cyan'}>{e.synthetic ? 'SYNTHETIC' : 'PROVIDER'}</Badge></td></tr>)}</tbody></table></div><p className="panel-note">Showing up to 100 rows. The export includes up to 2,000 recent observations.</p></section>}
    {tab === 'timeline' && <section className="panel"><PanelTitle title="Recorded milestones" eyebrow="NO INVENTED EXTERNAL CAUSES" /><div className="timeline">{detail?.timeline?.length ? detail.timeline.map((e, i) => <div key={`${e.occurred_at}-${i}`}><time>{date(e.occurred_at, true)} UTC</time><span><Badge tone="cyan">{e.kind}</Badge><p>{e.message}</p></span></div>) : <Empty title="No milestones recorded yet.">Future runs record threshold crossings, lifecycle changes and anomalies.</Empty>}</div></section>}
  </>;
}

function Providers({ providers }: { providers: Provider[] }) {
  return <><div className="provider-grid">{providers.map(p => <section className="panel provider-card" key={p.name}><div className="provider-heading"><span className="provider-icon"><Database size={23} /></span><div><h2>{({ demo: 'Demo engine', alpha_vantage: 'Alpha Vantage', youtube: 'YouTube Data API', github: 'GitHub REST API', google_trends: 'Google Trends' } as Record<string, string>)[p.name] || p.name}</h2><small className="micro">{p.capability}</small></div><Badge tone={p.status === 'ONLINE' ? 'lime' : p.status === 'NOT CONFIGURED' ? 'neutral' : 'amber'}>{p.status}</Badge></div><p>{p.message}</p><dl><div><dt>Last successful retrieval</dt><dd>{date(p.last_success, true)} UTC</dd></div><div><dt>Expected update interval</dt><dd>{p.expected_interval_hours} hours</dd></div><div><dt>Rows collected</dt><dd>{fmt(p.records, 0)}</dd></div><div><dt>Last run requests / success</dt><dd>{p.stats.requests ?? 0} / {p.stats.successes ?? 0}</dd></div><div><dt>Last request latency</dt><dd>{p.stats.latency_ms ?? '—'} ms</dd></div></dl></section>)}</div><div className="panel provider-notes"><PanelTitle title="What’s connected — and what isn’t" /><p>API adapters are implemented for daily financial OHLCV, public GitHub repositories and raw YouTube video statistics. Live keys and access must be configured on the server.</p><p>Google Trends, live fashion, live news, geographic interest, and semantic entity intelligence are not configured. Their synthetic examples never imply a working live source. Existing observations remain visible with their original timestamps if a provider fails.</p><p><code>DEMO_MODE=false</code> selects live providers. Keys stay in <code>.env</code>; they are never delivered to the browser.</p></div></>;
}

function Compare({ trends, onOpen, onError }: { trends: Trend[]; onOpen: (id: string) => void; onError: (message: string) => void }) {
  const [left, setLeft] = useState(trends[0]?.id || '');
  const [right, setRight] = useState(trends[1]?.id || '');
  const [relationship, setRelationship] = useState<Relationship | null>(null);
  const [busy, setBusy] = useState(false);
  const a = trends.find(t => t.id === left), b = trends.find(t => t.id === right);
  const inspect = async () => { setBusy(true); try { setRelationship(await api<Relationship>(`/api/relationships?left=${encodeURIComponent(left)}&right=${encodeURIComponent(right)}`)); } catch (e) { onError((e as Error).message); } finally { setBusy(false); } };
  return <><div className="comparison-selectors"><label>First signal<select value={left} onChange={e => { setLeft(e.target.value); setRelationship(null); }}>{trends.map(t => <option key={t.id} value={t.id}>{t.name}</option>)}</select></label><GitCompareArrows size={26} /><label>Second signal<select value={right} onChange={e => { setRight(e.target.value); setRelationship(null); }}>{trends.map(t => <option key={t.id} value={t.id}>{t.name}</option>)}</select></label></div>{a && b && <><div className="grid-two">{[a, b].map((t, i) => <section className="panel comparison-card" key={i}><PanelTitle title={t.name} eyebrow={domainNames[t.domain]} action={<button className="icon-button" aria-label={`Open ${t.name}`} onClick={() => onOpen(t.id)}><ArrowUpRight size={18} /></button>} /><LineChart points={t.sparkline} color={i ? 'var(--cyan)' : 'var(--lime)'} unit={t.unit} /><div className="comparison-stats">{[['Score', fmt(t.score.current_score)], ['Momentum', fmt(t.score.components?.momentum ?? undefined)], ['Acceleration', fmt(t.score.components?.acceleration ?? undefined)], ['Persistence', fmt(t.score.components?.persistence ?? undefined)], ['Lifecycle', t.score.lifecycle_stage || 'Unavailable'], ['Freshness', t.freshness.status]].map(([label, value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>{t.forecast && <Probability forecast={t.forecast} />}</section>)}</div><section className="panel"><PanelTitle title="Possible lead–lag relationship" eyebrow="EXPERIMENTAL / LOG CHANGES / ALIGNED UTC DATES" action={<button className="button primary" disabled={busy || left === right} onClick={() => void inspect()}>{busy ? 'Calculating…' : 'Explore correlation'} <ArrowRight size={16} /></button>} /><p className="panel-note">Searches lags from −14 to +14 calendar days using changes, not trending levels. Positive lag means the first signal leads. Correlation does not establish causation.</p>{relationship && <><div className="trust-stats"><span><strong>{fmt(relationship.correlation, 3)}</strong>Best-lag correlation</span><span><strong>{relationship.best_lag_days ?? '—'}</strong>Calendar-day lag</span><span><strong>{relationship.sample_size ?? 0}</strong>Aligned changes</span></div><p className="subtle-notice">{relationship.caution}</p><div className="correlation-bars" aria-label="Cross-correlation by lag">{relationship.samples.map(s => <div key={s.lag_days} title={`${s.lag_days} days: ${s.correlation.toFixed(3)}`}><i style={{ height: `${Math.abs(s.correlation) * 90 + 2}px`, background: s.correlation < 0 ? 'var(--coral)' : 'var(--cyan)' }} /><small>{s.lag_days}</small></div>)}</div></>}</section></>}</>;
}

function Reports({ onError }: { onError: (message: string) => void }) {
  const [reports, setReports] = useState<{ id: string; created_at: string; mode: string }[]>([]);
  useEffect(() => { api<{ items: typeof reports }>('/api/reports').then(r => setReports(r.items)).catch(e => onError(e.message)); }, [onError]);
  return <section className="panel"><PanelTitle title="Report archive" eyebrow="TIMESTAMPED / MARKDOWN + JSON + HTML" /><p className="panel-note">Reports are generated by each data-update run. They preserve the data mode and freshness at generation time.</p>{reports.length ? <div className="report-list">{reports.map(r => <div className="report-row" key={r.id}><span className="report-icon"><FileText size={26} /></span><div><h3>Trend intelligence report</h3><p>{date(r.created_at, true)} UTC</p><Badge tone={r.mode.includes('DEMO') ? 'amber' : 'cyan'}>{r.mode}</Badge></div><div className="report-actions">{['html', 'md', 'json'].map(format => <button key={format} className="button" onClick={() => download(`/api/reports/${r.id}?format=${format}`, `trendforge-report-${r.id.slice(0, 8)}.${format}`).catch(e => onError(e.message))}><Download size={14} />{format.toUpperCase()}</button>)}</div></div>)}</div> : <Empty title="No reports have been generated.">Run <code>trendforge report</code> after an update.</Empty>}</section>;
}

function Research({ trends, record, onError }: { trends: Trend[]; record: TrackRecord | null; onError: (message: string) => void }) {
  const [entity, setEntity] = useState(trends.find(t => t.analytics_allowed)?.id || '');
  const [horizon, setHorizon] = useState(7);
  const [method, setMethod] = useState('euclidean');
  const [result, setResult] = useState<Backtest | null>(null);
  const [busy, setBusy] = useState(false);
  const [models, setModels] = useState<{ id: string; status: string; card: Record<string, unknown> }[]>([]);
  useEffect(() => { api<{ items: typeof models }>('/api/models').then(r => setModels(r.items)).catch(e => onError(e.message)); }, [onError]);
  const run = async (event: FormEvent) => { event.preventDefault(); setBusy(true); try { setResult(await api<Backtest>('/api/experiments/backtest', { method: 'POST', body: JSON.stringify({ entity_id: entity, horizon, method, window: 21 }) })); } catch (e) { onError((e as Error).message); } finally { setBusy(false); } };
  return <><section className="panel track-panel"><PanelTitle title="The prospective track record" eyebrow="FORECASTS STORED BEFORE OUTCOMES ARE KNOWN" action={<Badge tone="amber">{record?.synthetic ? 'SYNTHETIC ONLY' : 'PROVIDER DATA'}</Badge>} /><div className="trust-stats"><span><strong>{record?.issued ?? 0}</strong>Issued</span><span><strong>{record?.pending ?? 0}</strong>Pending</span><span><strong>{record?.resolved ?? 0}</strong>Resolved</span><span><strong>{record?.metrics.accuracy === undefined ? '—' : `${fmt(record.metrics.accuracy * 100)}%`}</strong>Directional accuracy</span><span><strong>{fmt(record?.metrics.brier_score, 3)}</strong>Brier score</span></div><p className="panel-note">{record?.note}</p></section><div className="grid-two"><section className="panel"><PanelTitle title="Walk-forward experiment" eyebrow="RESEARCH ONLY / PRODUCTION UNCHANGED" /><form className="experiment-form" onSubmit={e => void run(e)}><label>Trend<select value={entity} onChange={e => setEntity(e.target.value)}>{trends.filter(t => t.analytics_allowed).map(t => <option key={t.id} value={t.id}>{t.name}</option>)}</select></label><div className="form-grid"><label>Horizon (observations)<select value={horizon} onChange={e => setHorizon(Number(e.target.value))}>{[1, 3, 5, 7, 14, 20, 30].map(n => <option key={n}>{n}</option>)}</select></label><label>Pattern distance<select value={method} onChange={e => setMethod(e.target.value)}><option value="euclidean">Euclidean</option><option value="cosine">Cosine</option><option value="correlation">Correlation</option></select></label></div><p className="small muted">Each forecast sees only the data available at its historical origin. Analogue outcomes are purged before the query window, and test outcome intervals do not overlap.</p><button className="button primary" disabled={busy || !entity}>{busy ? 'Evaluating historical origins…' : 'Run experiment'}<FlaskConical size={16} /></button></form></section><section className="panel"><PanelTitle title="Model registry" eyebrow="ENABLED BASELINE / VERSIONED METHOD" />{models.map(m => <div className="model-card" key={m.id}><h3>{m.id}</h3><Badge tone="cyan">{m.status}</Badge><p>{String(m.card.name)}</p><dl><div><dt>Calibration</dt><dd>{String(m.card.calibration)}</dd></div><div><dt>Confidence cap</dt><dd>{String(m.card.confidence_cap)}</dd></div><div><dt>Validation</dt><dd>{String(m.card.validation)}</dd></div></dl></div>)}<div className="subtle-notice"><ShieldCheck size={17} />Advanced models stay in research until sufficient prospective evidence supports promotion.</div></section></div>
    {result && <section className="panel experiment-result" aria-live="polite"><PanelTitle title="Experiment results" eyebrow={`${result.entity} / ${result.horizon}-OBSERVATION HORIZON`} action={<Badge tone="amber">{result.synthetic ? 'SYNTHETIC REPLAY' : 'RETROSPECTIVE REPLAY'}</Badge>} /><div className="trust-stats"><span><strong>{result.metrics.sample_size}</strong>Test origins</span><span><strong>{result.metrics.accuracy === undefined ? '—' : `${fmt(result.metrics.accuracy * 100)}%`}</strong>Accuracy</span><span><strong>{fmt(result.metrics.brier_score, 3)}</strong>Multiclass Brier</span><span><strong>{fmt(result.metrics.log_loss, 3)}</strong>Log loss</span><span><strong>{fmt(result.metrics.f1_macro, 3)}</strong>Macro F1</span></div><p className="panel-note">{result.validation}. Uniform three-class Brier baseline: 0.667. Lower Brier and log loss are better.</p>{result.metrics.reliability && <><h3 className="calibration-title">Growth probability reliability</h3><div className="reliability-chart"><svg viewBox="0 0 460 230" role="img" aria-label="Reliability diagram: predicted probability versus actual frequency"><line x1="45" y1="195" x2="435" y2="20" stroke="var(--border)" strokeDasharray="5 5" /><line x1="45" y1="195" x2="435" y2="195" stroke="var(--border)" /><line x1="45" y1="195" x2="45" y2="20" stroke="var(--border)" />{result.metrics.reliability.up.map((p, i) => <g key={i}><circle cx={45 + p.predicted_probability * 390} cy={195 - p.actual_frequency * 175} r={5 + Math.min(p.sample_size, 20) / 4} fill="var(--lime)" opacity=".8"><title>{`${fmt(p.predicted_probability * 100)}% predicted; ${fmt(p.actual_frequency * 100)}% observed; n=${p.sample_size}`}</title></circle><text x={45 + p.predicted_probability * 390} y={182 - p.actual_frequency * 175} textAnchor="middle" fill="var(--text)" fontSize="10">n={p.sample_size}</text></g>)}<text x="45" y="212" fill="var(--muted)" fontSize="10">0%</text><text x="414" y="212" fill="var(--muted)" fontSize="10">100%</text><text x="190" y="229" fill="var(--muted)" fontSize="11">Predicted probability →</text><text x="9" y="24" fill="var(--muted)" fontSize="10">100%</text><text x="14" y="195" fill="var(--muted)" fontSize="10">0%</text></svg><span className="small muted">Vertical axis: observed growth frequency. Bubble size: sample count. Small samples are unstable.</span></div></>}<ul className="reason-list">{result.limitations.map(l => <li key={l}>{l}</li>)}</ul></section>}
  </>;
}
